version: "3"

services:
  elasticsearch:
    image: sebp/elk
    container_name: elk
    volumes:
      - ./data/elasticsearch:/var/lib/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
      - 5044:5044
      - 5601:5601
    restart: on-failure
