version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mzabalza
      - MONGO_INITDB_ROOT_PASSWORD=thisismypassword
    volumes:
      - ./data:/data/db
    ports:
      - 10017:27017
    restart: on-failure
